#!/usr/bin/env python3
import csv
import re
import sys
from pathlib import Path

INPUT_CSV = Path('migration_data/orphan_profiles_email_template.csv')
OUT_SQL = Path('migration_data/option3_recreate_auth_users.sql')
OUT_REPORT = Path('migration_data/option3_prepare_report.txt')

EMAIL_RE = re.compile(r'^[^@\s]+@[^@\s]+\.[^@\s]+$')
UUID_RE = re.compile(r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$')


def sql_quote(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


if not INPUT_CSV.exists():
    print(f'Missing input file: {INPUT_CSV}', file=sys.stderr)
    sys.exit(1)

rows = []
errors = []
seen_ids = set()
seen_emails = set()

with INPUT_CSV.open(newline='') as f:
    reader = csv.DictReader(f)
    required = ['profile_id', 'email', 'temp_password', 'send_reset_email']
    missing_cols = [c for c in required if c not in reader.fieldnames]
    if missing_cols:
        print('Missing required columns: ' + ', '.join(missing_cols), file=sys.stderr)
        sys.exit(1)

    for i, r in enumerate(reader, start=2):
        profile_id = (r.get('profile_id') or '').strip()
        email = (r.get('email') or '').strip().lower()
        temp_password = (r.get('temp_password') or '').strip()
        send_reset_email = (r.get('send_reset_email') or '').strip().lower() in ('true', '1', 'yes', 'y')

        if not UUID_RE.match(profile_id):
            errors.append(f'Line {i}: invalid profile_id UUID: {profile_id}')
            continue
        if profile_id in seen_ids:
            errors.append(f'Line {i}: duplicate profile_id: {profile_id}')
            continue
        seen_ids.add(profile_id)

        if not email:
            errors.append(f'Line {i}: missing email for profile_id {profile_id}')
            continue
        if not EMAIL_RE.match(email):
            errors.append(f'Line {i}: invalid email format: {email}')
            continue
        if email in seen_emails:
            errors.append(f'Line {i}: duplicate email in file: {email}')
            continue
        seen_emails.add(email)

        if len(temp_password) < 12:
            errors.append(f'Line {i}: temp_password too short (<12) for profile_id {profile_id}')
            continue

        rows.append({
            'profile_id': profile_id,
            'email': email,
            'temp_password': temp_password,
            'send_reset_email': send_reset_email,
        })

report_lines = []
report_lines.append(f'total_rows={len(rows)}')
report_lines.append(f'errors={len(errors)}')
if errors:
    report_lines.append('')
    report_lines.append('[errors]')
    report_lines.extend(errors)

OUT_REPORT.write_text('\n'.join(report_lines) + '\n')

if errors:
    print('Validation failed. Fix the CSV first: ' + str(OUT_REPORT))
    sys.exit(2)

sql = []
sql.append('-- Generated by prepare_option3_sql.py')
sql.append('-- Safe mode: insert only missing auth users/identities, no updates, no deletes')
sql.append('BEGIN;')
sql.append('SET LOCAL statement_timeout = 0;')
sql.append('SET LOCAL lock_timeout = 0;')
sql.append('')

for r in rows:
    pid = sql_quote(r['profile_id'])
    em = sql_quote(r['email'])
    pw = sql_quote(r['temp_password'])

    sql.append(f'-- profile_id: {r["profile_id"]} | email: {r["email"]}')
    sql.append(
        "INSERT INTO auth.users ("
        "instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, "
        "created_at, updated_at, raw_app_meta_data, raw_user_meta_data, is_sso_user, is_anonymous"
        ") "
        "SELECT "
        "'00000000-0000-0000-0000-000000000000'::uuid, "
        f"{pid}::uuid, 'authenticated', 'authenticated', {em}, "
        f"crypt({pw}, gen_salt('bf')), now(), now(), now(), "
        "jsonb_build_object('provider','email','providers',jsonb_build_array('email')), '{}'::jsonb, false, false "
        f"WHERE NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = {pid}::uuid OR lower(u.email) = lower({em}));"
    )

    sql.append(
        'INSERT INTO auth.identities (provider_id, user_id, identity_data, provider, created_at, updated_at) '
        f"SELECT {pid}, {pid}::uuid, jsonb_build_object('sub', {pid}, 'email', {em}, 'email_verified', true), 'email', now(), now() "
        f'WHERE EXISTS (SELECT 1 FROM auth.users u WHERE u.id = {pid}::uuid) '
        f"AND NOT EXISTS (SELECT 1 FROM auth.identities i WHERE i.provider = 'email' AND i.user_id = {pid}::uuid);"
    )
    sql.append('')

sql.append('COMMIT;')

OUT_SQL.write_text('\n'.join(sql) + '\n')
print(f'Wrote {OUT_SQL}')
print(f'Wrote {OUT_REPORT}')
print(f'Prepared rows: {len(rows)}')
