-- Seed notification_templates with the email designs that are hard-coded in the
-- send-* edge functions, so the admin Notification Center can manage them.
-- Placeholders use {{variable}} syntax rendered by notification-dispatcher;
-- {{action_url}} is always provided by the dispatcher.
--
-- Safe to re-run: new types are inserted, and existing rows only get the
-- email/push columns that are still empty, so admin edits are never overwritten.

WITH seed(type, title_template, message_template, email_subject_template, email_html_template, email_text_template, push_title_template, push_body_template, variables) AS (
  VALUES
  -- send-join-status-notification
  ('join_approved', 'Request approved!', 'Your request to join "{{trip_title}}" has been approved', 'Your join request was approved', '<!doctype html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width" /><title>Ketravelan</title></head><body style="margin:0;background:#f4f6f8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial"><div style="display:none;font-size:1px;color:#f4f6f8;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden">Update on your join request</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 0;"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:520px;background:#ffffff;border-radius:16px;border:1px solid #e5e7eb;box-shadow:0 10px 28px rgba(15,23,42,.08);"><tr><td align="center" style="padding:24px 20px"><img src="https://ketravelan.com/ketravelan_logo.png" alt="Ketravelan" style="display:block;border:0;outline:none;text-decoration:none;height:28px;width:auto" /></td></tr><tr><td style="height:1px;background:#e5e7eb" aria-hidden="true"></td></tr><tr><td style="padding:28px"><h1 style="font-size:20px;font-weight:700;margin:0 0 8px;color:#020617;text-align:center">Your join request was approved</h1><div style="font-size:15px;line-height:1.65;color:#475569;margin-bottom:24px;text-align:center">Great news! You''ve been approved to join <strong>{{trip_title}}</strong> ({{trip_destination}}).</div><table role="presentation" cellspacing="0" cellpadding="0" width="100%"><tr><td align="center"><a href="{{action_url}}" target="_blank" style="display:inline-block;padding:14px 26px;border-radius:10px;background:#000000;color:#ffffff;text-decoration:none;font-weight:600">View Trip</a></td></tr></table></td></tr><tr><td style="padding:24px 28px;font-size:12px;color:#64748b;line-height:1.6">You’re receiving this because you requested to join a trip on Ketravelan.<br><br>If the button doesn’t work, copy this link:<br><a href="{{action_url}}" style="color:#2563eb;word-break:break-all">{{action_url}}</a><br><br><strong>The Ketravelan Crew</strong></td></tr></table></td></tr></table></body></html>', 'Your join request was approved

You''ve been approved to join {{trip_title}} ({{trip_destination}}).

{{action_url}}

The Ketravelan Crew', 'You are in! 🎉', 'Your request to join {{trip_title}} was approved', '["trip_title","trip_destination","action_url"]'::jsonb),
  -- send-join-status-notification
  ('join_rejected', 'Join request update', 'Your request to join "{{trip_title}}" was not approved', 'Your join request was declined', '<!doctype html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width" /><title>Ketravelan</title></head><body style="margin:0;background:#f4f6f8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial"><div style="display:none;font-size:1px;color:#f4f6f8;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden">Update on your join request</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 0;"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:520px;background:#ffffff;border-radius:16px;border:1px solid #e5e7eb;box-shadow:0 10px 28px rgba(15,23,42,.08);"><tr><td align="center" style="padding:24px 20px"><img src="https://ketravelan.com/ketravelan_logo.png" alt="Ketravelan" style="display:block;border:0;outline:none;text-decoration:none;height:28px;width:auto" /></td></tr><tr><td style="height:1px;background:#e5e7eb" aria-hidden="true"></td></tr><tr><td style="padding:28px"><h1 style="font-size:20px;font-weight:700;margin:0 0 8px;color:#020617;text-align:center">Your join request was declined</h1><div style="font-size:15px;line-height:1.65;color:#475569;margin-bottom:24px;text-align:center">We''re sorry, your request to join <strong>{{trip_title}}</strong> ({{trip_destination}}) was not approved this time.</div><table role="presentation" cellspacing="0" cellpadding="0" width="100%"><tr><td align="center"><a href="{{action_url}}" target="_blank" style="display:inline-block;padding:14px 26px;border-radius:10px;background:#000000;color:#ffffff;text-decoration:none;font-weight:600">Explore Trips</a></td></tr></table></td></tr><tr><td style="padding:24px 28px;font-size:12px;color:#64748b;line-height:1.6">You’re receiving this because you requested to join a trip on Ketravelan.<br><br>If the button doesn’t work, copy this link:<br><a href="{{action_url}}" style="color:#2563eb;word-break:break-all">{{action_url}}</a><br><br><strong>The Ketravelan Crew</strong></td></tr></table></td></tr></table></body></html>', 'Your join request was declined

Your request to join {{trip_title}} ({{trip_destination}}) was declined.

{{action_url}}

The Ketravelan Crew', 'Join request update', 'Your request to join {{trip_title}} was not approved', '["trip_title","trip_destination","action_url"]'::jsonb),
  -- send-trip-join-notification
  ('join_request', 'New join request', '{{requester_name}} wants to join {{trip_title}}', 'Join request for {{trip_title}}', '<!doctype html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width" /><title>Ketravelan</title></head><body style="margin:0;background:#f4f6f8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial"><div style="display:none;font-size:1px;color:#f4f6f8;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden">New join request on Ketravelan</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 0;"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:520px;background:#ffffff;border-radius:16px;border:1px solid #e5e7eb;box-shadow:0 10px 28px rgba(15,23,42,.08);"><tr><td align="center" style="padding:24px 20px"><img src="https://ketravelan.com/ketravelan_logo.png" alt="Ketravelan" style="display:block;border:0;outline:none;text-decoration:none;height:28px;width:auto" /></td></tr><tr><td style="height:1px;background:#e5e7eb" aria-hidden="true"></td></tr><tr><td style="padding:28px"><h1 style="font-size:20px;font-weight:700;margin:0 0 8px;color:#020617;text-align:center">New join request</h1><div style="font-size:15px;line-height:1.65;color:#475569;margin-bottom:24px;text-align:center">New request from <strong>{{requester_name}}</strong>.<br/>Trip: <strong>{{trip_title}}</strong> ({{trip_destination}})<br/><br/><em>Message:</em><br/>{{request_message}}</div><table role="presentation" cellspacing="0" cellpadding="0" width="100%"><tr><td align="center"><a href="{{action_url}}" target="_blank" style="display:inline-block;padding:14px 26px;border-radius:10px;background:#000000;color:#ffffff;text-decoration:none;font-weight:600">Review Request</a></td></tr></table></td></tr><tr><td style="padding:24px 28px;font-size:12px;color:#64748b;line-height:1.6">You’re receiving this because you created a trip on Ketravelan.<br><br>If the button doesn’t work, copy this link:<br><a href="{{action_url}}" style="color:#2563eb;word-break:break-all">{{action_url}}</a><br><br><strong>The Ketravelan Crew</strong></td></tr></table></td></tr></table></body></html>', 'New join request

New request from {{requester_name}} for {{trip_title}} ({{trip_destination}}).

Message: {{request_message}}

{{action_url}}

The Ketravelan Crew', 'New join request', '{{requester_name}} wants to join {{trip_title}}', '["requester_name","trip_title","trip_destination","request_message","action_url"]'::jsonb),
  -- send-trip-reminder-email
  ('trip_reminder', 'Trip reminder', 'Get ready for {{trip_title}}', 'Get ready! Your trip to {{trip_destination}} starts {{timeline_text}} ({{start_date}}) 🚀', '<!doctype html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width" /><title>Ketravelan</title></head><body style="margin:0;background:#f4f6f8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial"><div style="display:none;font-size:1px;color:#f4f6f8;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden">Your trip is coming up!</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 0;"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:520px;background:#ffffff;border-radius:16px;border:1px solid #e5e7eb;box-shadow:0 10px 28px rgba(15,23,42,.08);"><tr><td align="center" style="padding:24px 20px"><img src="https://ketravelan.com/ketravelan_logo.png" alt="Ketravelan" style="display:block;border:0;outline:none;text-decoration:none;height:28px;width:auto" /></td></tr><tr><td style="height:1px;background:#e5e7eb" aria-hidden="true"></td></tr><tr><td style="padding:28px"><h1 style="font-size:20px;font-weight:700;margin:0 0 8px;color:#020617;text-align:center">Your trip is coming up! 📅</h1><div style="font-size:15px;line-height:1.65;color:#475569;margin-bottom:24px;text-align:center">Hi <strong>{{recipient_name}}</strong>,<br><br>Your trip to <strong>{{trip_destination}}</strong> starts <strong>{{timeline_text}}</strong> on <strong>{{start_date}}</strong>.<br><br>Make sure everything is ready and review the trip details below!</div><table role="presentation" cellspacing="0" cellpadding="0" width="100%"><tr><td align="center"><a href="{{action_url}}" target="_blank" style="display:inline-block;padding:14px 26px;border-radius:10px;background:#000000;color:#ffffff;text-decoration:none;font-weight:600">View Trip</a></td></tr></table></td></tr><tr><td style="padding:24px 28px;font-size:12px;color:#64748b;line-height:1.6">You’re receiving this because you created a trip on Ketravelan.<br><br>If the button doesn’t work, copy this link:<br><a href="{{action_url}}" style="color:#2563eb;word-break:break-all">{{action_url}}</a><br><br><strong>The Ketravelan Crew</strong></td></tr></table></td></tr></table></body></html>', 'Your trip is coming up! 📅

Hi {{recipient_name}},

Your trip to {{trip_destination}} starts {{timeline_text}} on {{start_date}}.

{{action_url}}

The Ketravelan Crew', 'Trip reminder', '🌄 Get ready for {{trip_title}}', '["recipient_name","trip_title","trip_destination","timeline_text","start_date","action_url"]'::jsonb),
  -- create-trip-invite
  ('trip_invite', 'You''re invited!', '{{inviter_name}} invited you to join {{trip_title}}.', 'You are invited: {{trip_title}}', '<!doctype html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width" /><title>Ketravelan</title></head><body style="margin:0;background:#f4f6f8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial"><div style="display:none;font-size:1px;color:#f4f6f8;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden">Your spot is waiting for {{trip_title}}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 0;"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:520px;background:#ffffff;border-radius:16px;border:1px solid #e5e7eb;box-shadow:0 10px 28px rgba(15,23,42,.08);"><tr><td align="center" style="padding:24px 20px"><img src="https://ketravelan.com/ketravelan_logo.png" alt="Ketravelan" style="display:block;border:0;outline:none;text-decoration:none;height:28px;width:auto" /></td></tr><tr><td style="height:1px;background:#e5e7eb" aria-hidden="true"></td></tr><tr><td style="padding:28px"><h1 style="font-size:20px;font-weight:700;margin:0 0 8px;color:#020617;text-align:center">You''re invited! ✈️</h1><div style="font-size:15px;line-height:1.65;color:#475569;margin-bottom:24px;text-align:center"><strong>{{inviter_name}}</strong> wants you on this trip.<br><br><strong>{{trip_title}}</strong><br>Confirm to secure your spot and meet the crew.</div><table role="presentation" cellspacing="0" cellpadding="0" width="100%"><tr><td align="center"><a href="{{action_url}}" target="_blank" style="display:inline-block;padding:14px 26px;border-radius:10px;background:#000000;color:#ffffff;text-decoration:none;font-weight:600">Accept Invite</a></td></tr></table></td></tr><tr><td style="padding:24px 28px;font-size:12px;color:#64748b;line-height:1.6">You’re receiving this because you have a Ketravelan account.<br><br>If the button doesn’t work, copy this link:<br><a href="{{action_url}}" style="color:#2563eb;word-break:break-all">{{action_url}}</a><br><br><strong>The Ketravelan Crew</strong></td></tr></table></td></tr></table></body></html>', 'You''re invited! ✈️

{{inviter_name}} invited you to join {{trip_title}}.

{{action_url}}

The Ketravelan Crew', 'Trip invite', '{{inviter_name}} invited you to join {{trip_title}}', '["inviter_name","trip_title","action_url"]'::jsonb),
  -- send-trip-created-email
  ('trip_created', 'Your trip is live!', 'Your trip "{{trip_title}}" is now live', 'Your trip "{{trip_title}}" is now live! 🚀', '<!doctype html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width" /><title>Ketravelan</title></head><body style="margin:0;background:#f4f6f8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial"><div style="display:none;font-size:1px;color:#f4f6f8;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden">Your trip on Ketravelan is live!</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 0;"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:520px;background:#ffffff;border-radius:16px;border:1px solid #e5e7eb;box-shadow:0 10px 28px rgba(15,23,42,.08);"><tr><td align="center" style="padding:24px 20px"><img src="https://ketravelan.com/ketravelan_logo.png" alt="Ketravelan" style="display:block;border:0;outline:none;text-decoration:none;height:28px;width:auto" /></td></tr><tr><td style="height:1px;background:#e5e7eb" aria-hidden="true"></td></tr><tr><td style="padding:28px"><h1 style="font-size:20px;font-weight:700;margin:0 0 8px;color:#020617;text-align:center">Your Trip is Live! 🎉</h1><div style="font-size:15px;line-height:1.65;color:#475569;margin-bottom:24px;text-align:center">Hi <strong>{{recipient_name}}</strong>,<br><br>Your trip to <strong>{{trip_destination}}</strong> is now published and ready for travelers to join!<br><br>Share it with friends or let travelers discover it on Ketravelan.</div><table role="presentation" cellspacing="0" cellpadding="0" width="100%"><tr><td align="center"><a href="{{action_url}}" target="_blank" style="display:inline-block;padding:14px 26px;border-radius:10px;background:#000000;color:#ffffff;text-decoration:none;font-weight:600">View Trip</a></td></tr></table></td></tr><tr><td style="padding:24px 28px;font-size:12px;color:#64748b;line-height:1.6">You’re receiving this because you created a trip on Ketravelan.<br><br>If the button doesn’t work, copy this link:<br><a href="{{action_url}}" style="color:#2563eb;word-break:break-all">{{action_url}}</a><br><br><strong>The Ketravelan Crew</strong></td></tr></table></td></tr></table></body></html>', 'Your Trip is Live! 🎉

Hi {{recipient_name}},

Your trip to {{trip_destination}} is now published and ready for travelers to join!

{{action_url}}

The Ketravelan Crew', 'Your trip is live! 🎉', '{{trip_title}} is now published', '["recipient_name","trip_title","trip_destination","action_url"]'::jsonb),
  -- send-trip-ended
  ('trip_ended', 'Trip wrapped', 'Your trip {{trip_title}} has wrapped up', 'Trip wrapped: {{trip_title}}', '<!doctype html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width" /><title>Ketravelan</title></head><body style="margin:0;background:#f4f6f8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial"><div style="display:none;font-size:1px;color:#f4f6f8;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden">Trip wrapped up on Ketravelan</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 0;"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:520px;background:#ffffff;border-radius:16px;border:1px solid #e5e7eb;box-shadow:0 10px 28px rgba(15,23,42,.08);"><tr><td align="center" style="padding:24px 20px"><img src="https://ketravelan.com/ketravelan_logo.png" alt="Ketravelan" style="display:block;border:0;outline:none;text-decoration:none;height:28px;width:auto" /></td></tr><tr><td style="height:1px;background:#e5e7eb" aria-hidden="true"></td></tr><tr><td style="padding:28px"><h1 style="font-size:20px;font-weight:700;margin:0 0 8px;color:#020617;text-align:center">Trip wrapped 🏁</h1><div style="font-size:15px;line-height:1.65;color:#475569;margin-bottom:24px;text-align:center">Hi <strong>{{recipient_name}}</strong>,<br><br>Your trip to <strong>{{trip_destination}}</strong> wrapped on <strong>{{end_date}}</strong>.<br><br>Hope it was a blast. You can review the trip details and keep any final notes or expenses in one place.</div><table role="presentation" cellspacing="0" cellpadding="0" width="100%"><tr><td align="center"><a href="{{action_url}}" target="_blank" style="display:inline-block;padding:14px 26px;border-radius:10px;background:#000000;color:#ffffff;text-decoration:none;font-weight:600">View Trip</a></td></tr></table></td></tr><tr><td style="padding:24px 28px;font-size:12px;color:#64748b;line-height:1.6">You’re receiving this because you created a trip on Ketravelan.<br><br>If the button doesn’t work, copy this link:<br><a href="{{action_url}}" style="color:#2563eb;word-break:break-all">{{action_url}}</a><br><br><strong>The Ketravelan Crew</strong></td></tr></table></td></tr></table></body></html>', 'Trip wrapped 🏁

Hi {{recipient_name}},

Your trip to {{trip_destination}} wrapped on {{end_date}}.

{{action_url}}

The Ketravelan Crew', 'Trip wrapped 🏁', '{{trip_title}} has ended', '["recipient_name","trip_title","trip_destination","end_date","action_url"]'::jsonb),
  -- send-trip-ended-expenses-complete
  ('trip_completed', 'Trip complete', '{{trip_title}} is complete and all expenses are settled', 'Trip complete: {{trip_title}}', '<!doctype html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width" /><title>Ketravelan</title></head><body style="margin:0;background:#f4f6f8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial"><div style="display:none;font-size:1px;color:#f4f6f8;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden">Trip complete on Ketravelan</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 0;"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:520px;background:#ffffff;border-radius:16px;border:1px solid #e5e7eb;box-shadow:0 10px 28px rgba(15,23,42,.08);"><tr><td align="center" style="padding:24px 20px"><img src="https://ketravelan.com/ketravelan_logo.png" alt="Ketravelan" style="display:block;border:0;outline:none;text-decoration:none;height:28px;width:auto" /></td></tr><tr><td style="height:1px;background:#e5e7eb" aria-hidden="true"></td></tr><tr><td style="padding:28px"><h1 style="font-size:20px;font-weight:700;margin:0 0 8px;color:#020617;text-align:center">Trip complete ✅</h1><div style="font-size:15px;line-height:1.65;color:#475569;margin-bottom:24px;text-align:center">Hi <strong>{{recipient_name}}</strong>,<br><br>Your trip to <strong>{{trip_destination}}</strong> wrapped on <strong>{{end_date}}</strong>, and all expenses are settled.<br><br>Nice work keeping everything tidy. You can review the trip summary anytime.</div><table role="presentation" cellspacing="0" cellpadding="0" width="100%"><tr><td align="center"><a href="{{action_url}}" target="_blank" style="display:inline-block;padding:14px 26px;border-radius:10px;background:#000000;color:#ffffff;text-decoration:none;font-weight:600">View Trip</a></td></tr></table></td></tr><tr><td style="padding:24px 28px;font-size:12px;color:#64748b;line-height:1.6">You’re receiving this because you created a trip on Ketravelan.<br><br>If the button doesn’t work, copy this link:<br><a href="{{action_url}}" style="color:#2563eb;word-break:break-all">{{action_url}}</a><br><br><strong>The Ketravelan Crew</strong></td></tr></table></td></tr></table></body></html>', 'Trip complete ✅

Hi {{recipient_name}},

Your trip to {{trip_destination}} wrapped on {{end_date}}, and all expenses are settled.

{{action_url}}

The Ketravelan Crew', 'Trip complete ✅', '{{trip_title}} is complete and all expenses are settled', '["recipient_name","trip_title","trip_destination","end_date","action_url"]'::jsonb),
  -- send-trip-participant-joined
  ('member_joined', 'New traveler joined', '{{participant_name}} joined {{trip_title}}', 'Fresh energy on your trip: {{trip_title}}', '<!doctype html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width" /><title>Ketravelan</title></head><body style="margin:0;background:#f4f6f8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial"><div style="display:none;font-size:1px;color:#f4f6f8;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden">New join alert on Ketravelan</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 0;"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:520px;background:#ffffff;border-radius:16px;border:1px solid #e5e7eb;box-shadow:0 10px 28px rgba(15,23,42,.08);"><tr><td align="center" style="padding:24px 20px"><img src="https://ketravelan.com/ketravelan_logo.png" alt="Ketravelan" style="display:block;border:0;outline:none;text-decoration:none;height:28px;width:auto" /></td></tr><tr><td style="height:1px;background:#e5e7eb" aria-hidden="true"></td></tr><tr><td style="padding:28px"><h1 style="font-size:20px;font-weight:700;margin:0 0 8px;color:#020617;text-align:center">New traveler joined 🙌</h1><div style="font-size:15px;line-height:1.65;color:#475569;margin-bottom:24px;text-align:center">You just got a new traveler, <strong>{{participant_name}}</strong>, on <strong>{{trip_title}}</strong> ({{trip_destination}}).</div><table role="presentation" cellspacing="0" cellpadding="0" width="100%"><tr><td align="center"><a href="{{action_url}}" target="_blank" style="display:inline-block;padding:14px 26px;border-radius:10px;background:#000000;color:#ffffff;text-decoration:none;font-weight:600">View Trip</a></td></tr></table></td></tr><tr><td style="padding:24px 28px;font-size:12px;color:#64748b;line-height:1.6">You’re receiving this because you created a trip on Ketravelan.<br><br>If the button doesn’t work, copy this link:<br><a href="{{action_url}}" style="color:#2563eb;word-break:break-all">{{action_url}}</a><br><br><strong>The Ketravelan Crew</strong></td></tr></table></td></tr></table></body></html>', 'New traveler joined 🙌

{{participant_name}} joined {{trip_title}} ({{trip_destination}}).

{{action_url}}

The Ketravelan Crew', 'New traveler joined 🙌', '{{participant_name}} joined {{trip_title}}', '["participant_name","trip_title","trip_destination","action_url"]'::jsonb),
  -- send-trip-invite-accepted
  ('trip_invite_accepted', 'Invite accepted', '{{invitee_name}} accepted your invitation for {{trip_title}}', 'Invite accepted: {{trip_title}}', '<!doctype html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width" /><title>Ketravelan</title></head><body style="margin:0;background:#f4f6f8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial"><div style="display:none;font-size:1px;color:#f4f6f8;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden">Invite accepted on Ketravelan</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 0;"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:520px;background:#ffffff;border-radius:16px;border:1px solid #e5e7eb;box-shadow:0 10px 28px rgba(15,23,42,.08);"><tr><td align="center" style="padding:24px 20px"><img src="https://ketravelan.com/ketravelan_logo.png" alt="Ketravelan" style="display:block;border:0;outline:none;text-decoration:none;height:28px;width:auto" /></td></tr><tr><td style="height:1px;background:#e5e7eb" aria-hidden="true"></td></tr><tr><td style="padding:28px"><h1 style="font-size:20px;font-weight:700;margin:0 0 8px;color:#020617;text-align:center">Invite accepted 🎉</h1><div style="font-size:15px;line-height:1.65;color:#475569;margin-bottom:24px;text-align:center"><strong>{{invitee_name}}</strong> accepted your invitation for <strong>{{trip_title}}</strong> ({{trip_destination}}).</div><table role="presentation" cellspacing="0" cellpadding="0" width="100%"><tr><td align="center"><a href="{{action_url}}" target="_blank" style="display:inline-block;padding:14px 26px;border-radius:10px;background:#000000;color:#ffffff;text-decoration:none;font-weight:600">View Trip</a></td></tr></table></td></tr><tr><td style="padding:24px 28px;font-size:12px;color:#64748b;line-height:1.6">You’re receiving this because you created a trip on Ketravelan.<br><br>If the button doesn’t work, copy this link:<br><a href="{{action_url}}" style="color:#2563eb;word-break:break-all">{{action_url}}</a><br><br><strong>The Ketravelan Crew</strong></td></tr></table></td></tr></table></body></html>', 'Invite accepted 🎉

{{invitee_name}} accepted your invitation for {{trip_title}} ({{trip_destination}}).

{{action_url}}

The Ketravelan Crew', 'Invite accepted 🎉', '{{invitee_name}} accepted your invitation for {{trip_title}}', '["invitee_name","trip_title","trip_destination","action_url"]'::jsonb),
  -- send-trip-cancelled
  ('trip_cancelled', 'Trip cancelled', '{{trip_title}} has been cancelled', 'Trip cancelled: {{trip_title}}', '<!doctype html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width" /><title>Ketravelan</title></head><body style="margin:0;background:#f4f6f8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial"><div style="display:none;font-size:1px;color:#f4f6f8;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden">Trip cancelled on Ketravelan</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 0;"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:520px;background:#ffffff;border-radius:16px;border:1px solid #e5e7eb;box-shadow:0 10px 28px rgba(15,23,42,.08);"><tr><td align="center" style="padding:24px 20px"><img src="https://ketravelan.com/ketravelan_logo.png" alt="Ketravelan" style="display:block;border:0;outline:none;text-decoration:none;height:28px;width:auto" /></td></tr><tr><td style="height:1px;background:#e5e7eb" aria-hidden="true"></td></tr><tr><td style="padding:28px"><h1 style="font-size:20px;font-weight:700;margin:0 0 8px;color:#020617;text-align:center">Trip cancelled</h1><div style="font-size:15px;line-height:1.65;color:#475569;margin-bottom:24px;text-align:center">Your trip <strong>{{trip_title}}</strong> ({{trip_destination}}) has been cancelled.<br/><br/>{{reason}}<br/><br/>No stress, there are more trips waiting for you.</div><table role="presentation" cellspacing="0" cellpadding="0" width="100%"><tr><td align="center"><a href="{{action_url}}" target="_blank" style="display:inline-block;padding:14px 26px;border-radius:10px;background:#000000;color:#ffffff;text-decoration:none;font-weight:600">Find Another Trip</a></td></tr></table></td></tr><tr><td style="padding:24px 28px;font-size:12px;color:#64748b;line-height:1.6">You’re receiving this because you’re part of a trip on Ketravelan.<br><br>If the button doesn’t work, copy this link:<br><a href="{{action_url}}" style="color:#2563eb;word-break:break-all">{{action_url}}</a><br><br><strong>The Ketravelan Crew</strong></td></tr></table></td></tr></table></body></html>', 'Trip cancelled

Your trip {{trip_title}} ({{trip_destination}}) has been cancelled.

{{reason}}

{{action_url}}

The Ketravelan Crew', 'Trip cancelled', '{{trip_title}} has been cancelled', '["trip_title","trip_destination","reason","action_url"]'::jsonb),
  -- send-expense-added
  ('new_expense', 'New expense added', '{{expense_description}} - You owe {{currency}} {{amount}}', 'New expense added: you owe {{currency}} {{amount}}', '<!doctype html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width" /><title>Ketravelan</title></head><body style="margin:0;background:#f4f6f8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial"><div style="display:none;font-size:1px;color:#f4f6f8;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden">You have a new expense</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 0;"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:520px;background:#ffffff;border-radius:16px;border:1px solid #e5e7eb;box-shadow:0 10px 28px rgba(15,23,42,.08);"><tr><td align="center" style="padding:24px 20px"><img src="https://ketravelan.com/ketravelan_logo.png" alt="Ketravelan" style="display:block;border:0;outline:none;text-decoration:none;height:28px;width:auto" /></td></tr><tr><td style="height:1px;background:#e5e7eb" aria-hidden="true"></td></tr><tr><td style="padding:28px"><h1 style="font-size:20px;font-weight:700;margin:0 0 8px;color:#020617;text-align:center">New expense added</h1><div style="font-size:15px;line-height:1.65;color:#475569;margin-bottom:24px;text-align:center">Heads up, <strong>{{payer_name}}</strong> added <strong>{{expense_description}}</strong> in <strong>{{trip_title}}</strong>. Your share is <strong>{{currency}} {{amount}}</strong>.</div><table role="presentation" cellspacing="0" cellpadding="0" width="100%"><tr><td align="center"><a href="{{action_url}}" target="_blank" style="display:inline-block;padding:14px 26px;border-radius:10px;background:#000000;color:#ffffff;text-decoration:none;font-weight:600">View Expense</a></td></tr></table></td></tr><tr><td style="padding:24px 28px;font-size:12px;color:#64748b;line-height:1.6">You’re receiving this because you’re part of a shared expense on Ketravelan.<br><br>If the button doesn’t work, copy this link:<br><a href="{{action_url}}" style="color:#2563eb;word-break:break-all">{{action_url}}</a><br><br><strong>The Ketravelan Crew</strong></td></tr></table></td></tr></table></body></html>', 'New expense added

{{payer_name}} added {{expense_description}} in {{trip_title}}. Your share is {{currency}} {{amount}}.

{{action_url}}

The Ketravelan Crew', 'New expense added', '{{expense_description}} - You owe {{currency}} {{amount}}', '["payer_name","expense_description","trip_title","currency","amount","action_url"]'::jsonb),
  -- send-expense-updated
  ('expense_updated', 'Expense updated', '{{expense_description}} in {{trip_title}} was updated', 'Expense updated: {{expense_description}}', '<!doctype html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width" /><title>Ketravelan</title></head><body style="margin:0;background:#f4f6f8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial"><div style="display:none;font-size:1px;color:#f4f6f8;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden">An expense was updated</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 0;"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:520px;background:#ffffff;border-radius:16px;border:1px solid #e5e7eb;box-shadow:0 10px 28px rgba(15,23,42,.08);"><tr><td align="center" style="padding:24px 20px"><img src="https://ketravelan.com/ketravelan_logo.png" alt="Ketravelan" style="display:block;border:0;outline:none;text-decoration:none;height:28px;width:auto" /></td></tr><tr><td style="height:1px;background:#e5e7eb" aria-hidden="true"></td></tr><tr><td style="padding:28px"><h1 style="font-size:20px;font-weight:700;margin:0 0 8px;color:#020617;text-align:center">Expense updated</h1><div style="font-size:15px;line-height:1.65;color:#475569;margin-bottom:24px;text-align:center">Heads up, <strong>{{expense_description}}</strong> in <strong>{{trip_title}}</strong> was updated. Check the latest details inside.</div><table role="presentation" cellspacing="0" cellpadding="0" width="100%"><tr><td align="center"><a href="{{action_url}}" target="_blank" style="display:inline-block;padding:14px 26px;border-radius:10px;background:#000000;color:#ffffff;text-decoration:none;font-weight:600">View Expense</a></td></tr></table></td></tr><tr><td style="padding:24px 28px;font-size:12px;color:#64748b;line-height:1.6">You’re receiving this because you’re part of a shared expense on Ketravelan.<br><br>If the button doesn’t work, copy this link:<br><a href="{{action_url}}" style="color:#2563eb;word-break:break-all">{{action_url}}</a><br><br><strong>The Ketravelan Crew</strong></td></tr></table></td></tr></table></body></html>', 'Expense updated

{{expense_description}} in {{trip_title}} was updated.

{{action_url}}

The Ketravelan Crew', 'Expense updated', '{{expense_description}} in {{trip_title}} was updated', '["expense_description","trip_title","action_url"]'::jsonb),
  -- send-expense-deleted
  ('expense_deleted', 'Expense deleted', '{{expense_description}} in {{trip_title}} was deleted', 'Expense deleted: {{expense_description}}', '<!doctype html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width" /><title>Ketravelan</title></head><body style="margin:0;background:#f4f6f8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial"><div style="display:none;font-size:1px;color:#f4f6f8;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden">An expense was deleted</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 0;"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:520px;background:#ffffff;border-radius:16px;border:1px solid #e5e7eb;box-shadow:0 10px 28px rgba(15,23,42,.08);"><tr><td align="center" style="padding:24px 20px"><img src="https://ketravelan.com/ketravelan_logo.png" alt="Ketravelan" style="display:block;border:0;outline:none;text-decoration:none;height:28px;width:auto" /></td></tr><tr><td style="height:1px;background:#e5e7eb" aria-hidden="true"></td></tr><tr><td style="padding:28px"><h1 style="font-size:20px;font-weight:700;margin:0 0 8px;color:#020617;text-align:center">Expense deleted</h1><div style="font-size:15px;line-height:1.65;color:#475569;margin-bottom:24px;text-align:center">The expense <strong>{{expense_description}}</strong> in <strong>{{trip_title}}</strong> was deleted. Your totals will update automatically.</div><table role="presentation" cellspacing="0" cellpadding="0" width="100%"><tr><td align="center"><a href="{{action_url}}" target="_blank" style="display:inline-block;padding:14px 26px;border-radius:10px;background:#000000;color:#ffffff;text-decoration:none;font-weight:600">View Trip</a></td></tr></table></td></tr><tr><td style="padding:24px 28px;font-size:12px;color:#64748b;line-height:1.6">You’re receiving this because you’re part of a shared expense on Ketravelan.<br><br>If the button doesn’t work, copy this link:<br><a href="{{action_url}}" style="color:#2563eb;word-break:break-all">{{action_url}}</a><br><br><strong>The Ketravelan Crew</strong></td></tr></table></td></tr></table></body></html>', 'Expense deleted

The expense {{expense_description}} in {{trip_title}} was deleted.

{{action_url}}

The Ketravelan Crew', 'Expense deleted', '{{expense_description}} in {{trip_title}} was deleted', '["expense_description","trip_title","action_url"]'::jsonb),
  -- send-expense-payment-marked
  ('expense_paid', 'Payment received ✅', '{{participant_name}} marked {{currency}} {{amount}} as paid', 'Payment received: {{currency}} {{amount}} from {{participant_name}}', '<!doctype html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width" /><title>Ketravelan</title></head><body style="margin:0;background:#f4f6f8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial"><div style="display:none;font-size:1px;color:#f4f6f8;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden">A payment was marked as paid</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 0;"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:520px;background:#ffffff;border-radius:16px;border:1px solid #e5e7eb;box-shadow:0 10px 28px rgba(15,23,42,.08);"><tr><td align="center" style="padding:24px 20px"><img src="https://ketravelan.com/ketravelan_logo.png" alt="Ketravelan" style="display:block;border:0;outline:none;text-decoration:none;height:28px;width:auto" /></td></tr><tr><td style="height:1px;background:#e5e7eb" aria-hidden="true"></td></tr><tr><td style="padding:28px"><h1 style="font-size:20px;font-weight:700;margin:0 0 8px;color:#020617;text-align:center">Payment received ✅</h1><div style="font-size:15px;line-height:1.65;color:#475569;margin-bottom:24px;text-align:center"><strong>{{participant_name}}</strong> marked <strong>{{currency}} {{amount}}</strong> as paid in <strong>{{trip_title}}</strong>.</div><table role="presentation" cellspacing="0" cellpadding="0" width="100%"><tr><td align="center"><a href="{{action_url}}" target="_blank" style="display:inline-block;padding:14px 26px;border-radius:10px;background:#000000;color:#ffffff;text-decoration:none;font-weight:600">View Settlement</a></td></tr></table></td></tr><tr><td style="padding:24px 28px;font-size:12px;color:#64748b;line-height:1.6">You’re receiving this because you’re part of a shared expense on Ketravelan.<br><br>If the button doesn’t work, copy this link:<br><a href="{{action_url}}" style="color:#2563eb;word-break:break-all">{{action_url}}</a><br><br><strong>The Ketravelan Crew</strong></td></tr></table></td></tr></table></body></html>', 'Payment received ✅

{{participant_name}} marked {{currency}} {{amount}} as paid in {{trip_title}}.

{{action_url}}

The Ketravelan Crew', 'Payment received ✅', '{{participant_name}} paid {{currency}} {{amount}}', '["participant_name","currency","amount","trip_title","action_url"]'::jsonb),
  -- send-expense-overdue-reminder
  ('expense_reminder', 'Expense Overdue Reminder', 'Your share for {{expense_description}} is still pending', 'Payment reminder: action needed', '<!doctype html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width" /><title>Ketravelan</title></head><body style="margin:0;background:#f4f6f8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial"><div style="display:none;font-size:1px;color:#f4f6f8;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden">You have a pending payment</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 0;"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:520px;background:#ffffff;border-radius:16px;border:1px solid #e5e7eb;box-shadow:0 10px 28px rgba(15,23,42,.08);"><tr><td align="center" style="padding:24px 20px"><img src="https://ketravelan.com/ketravelan_logo.png" alt="Ketravelan" style="display:block;border:0;outline:none;text-decoration:none;height:28px;width:auto" /></td></tr><tr><td style="height:1px;background:#e5e7eb" aria-hidden="true"></td></tr><tr><td style="padding:28px"><h1 style="font-size:20px;font-weight:700;margin:0 0 8px;color:#020617;text-align:center">Payment reminder</h1><div style="font-size:15px;line-height:1.65;color:#475569;margin-bottom:24px;text-align:center">Your share for <strong>{{expense_description}}</strong> is still pending. Amount: <strong>{{currency}} {{amount}}</strong>.</div><table role="presentation" cellspacing="0" cellpadding="0" width="100%"><tr><td align="center"><a href="{{action_url}}" target="_blank" style="display:inline-block;padding:14px 26px;border-radius:10px;background:#000000;color:#ffffff;text-decoration:none;font-weight:600">View Expense</a></td></tr></table></td></tr><tr><td style="padding:24px 28px;font-size:12px;color:#64748b;line-height:1.6">You’re receiving this because you’re part of a shared expense on Ketravelan.<br><br>If the button doesn’t work, copy this link:<br><a href="{{action_url}}" style="color:#2563eb;word-break:break-all">{{action_url}}</a><br><br><strong>The Ketravelan Crew</strong></td></tr></table></td></tr></table></body></html>', 'Payment reminder

Your share for {{expense_description}} is still pending. Amount: {{currency}} {{amount}}.

{{action_url}}

The Ketravelan Crew', 'Expense Overdue Reminder', '{{expense_description}} - {{currency}} {{amount}} pending', '["expense_description","currency","amount","action_url"]'::jsonb),
  -- send-payment-reminder / send-settlement-reminder
  ('payment_reminder', 'Payment reminder', '{{payer_name}} sent a reminder for {{currency}} {{amount}}', 'Payment Reminder: {{expense_description}} - {{trip_title}}', '<!doctype html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width" /><title>Ketravelan</title></head><body style="margin:0;background:#f4f6f8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial"><div style="display:none;font-size:1px;color:#f4f6f8;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden">Payment reminder for {{expense_description}}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 0;"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:520px;background:#ffffff;border-radius:16px;border:1px solid #e5e7eb;box-shadow:0 10px 28px rgba(15,23,42,.08);"><tr><td align="center" style="padding:24px 20px"><img src="https://ketravelan.com/ketravelan_logo.png" alt="Ketravelan" style="display:block;border:0;outline:none;text-decoration:none;height:28px;width:auto" /></td></tr><tr><td style="height:1px;background:#e5e7eb" aria-hidden="true"></td></tr><tr><td style="padding:28px"><h1 style="font-size:20px;font-weight:700;margin:0 0 8px;color:#020617;text-align:center">Payment Reminder</h1><div style="font-size:15px;line-height:1.65;color:#475569;margin-bottom:24px;text-align:center">Hi <strong>{{recipient_name}}</strong>,<br><br><strong>{{payer_name}}</strong> sent a friendly reminder for <strong>{{expense_description}}</strong> in <strong>{{trip_title}}</strong>.<br><br>Amount due: <strong>{{currency}} {{amount}}</strong></div><table role="presentation" cellspacing="0" cellpadding="0" width="100%"><tr><td align="center"><a href="{{action_url}}" target="_blank" style="display:inline-block;padding:14px 26px;border-radius:10px;background:#000000;color:#ffffff;text-decoration:none;font-weight:600">View Trip</a></td></tr></table></td></tr><tr><td style="padding:24px 28px;font-size:12px;color:#64748b;line-height:1.6">You’re receiving this because you’re part of a shared expense on Ketravelan.<br><br>If the button doesn’t work, copy this link:<br><a href="{{action_url}}" style="color:#2563eb;word-break:break-all">{{action_url}}</a><br><br><strong>The Ketravelan Crew</strong></td></tr></table></td></tr></table></body></html>', 'Payment Reminder

Hi {{recipient_name}},

{{payer_name}} sent a reminder for {{expense_description}} in {{trip_title}}. Amount due: {{currency}} {{amount}}.

{{action_url}}

The Ketravelan Crew', 'Payment reminder', '{{payer_name}} reminded you about {{currency}} {{amount}}', '["recipient_name","payer_name","expense_description","trip_title","currency","amount","action_url"]'::jsonb),
  -- send-welcome-email
  ('welcome', 'Welcome to Ketravelan', 'You''re all set! Start planning your next adventure.', 'Thank you for onboarding with Ketravelan', '<!doctype html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width" /><title>Ketravelan</title></head><body style="margin:0;background:#f4f6f8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial"><div style="display:none;font-size:1px;color:#f4f6f8;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden">You''re all set on Ketravelan!</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 0;"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:520px;background:#ffffff;border-radius:16px;border:1px solid #e5e7eb;box-shadow:0 10px 28px rgba(15,23,42,.08);"><tr><td align="center" style="padding:24px 20px"><img src="https://ketravelan.com/ketravelan_logo.png" alt="Ketravelan" style="display:block;border:0;outline:none;text-decoration:none;height:28px;width:auto" /></td></tr><tr><td style="height:1px;background:#e5e7eb" aria-hidden="true"></td></tr><tr><td style="padding:28px"><h1 style="font-size:20px;font-weight:700;margin:0 0 8px;color:#020617;text-align:center">You''re all set! 🎉</h1><div style="font-size:15px;line-height:1.65;color:#475569;margin-bottom:24px;text-align:center">Hi <strong>{{recipient_name}}</strong>,<br><br>Discover trips, connect with fellow travelers, and start planning your next adventure.</div><table role="presentation" cellspacing="0" cellpadding="0" width="100%"><tr><td align="center"><a href="{{action_url}}" target="_blank" style="display:inline-block;padding:14px 26px;border-radius:10px;background:#000000;color:#ffffff;text-decoration:none;font-weight:600">Explore Trips</a></td></tr></table></td></tr><tr><td style="padding:24px 28px;font-size:12px;color:#64748b;line-height:1.6">You’re receiving this because you have a Ketravelan account.<br><br>If the button doesn’t work, copy this link:<br><a href="{{action_url}}" style="color:#2563eb;word-break:break-all">{{action_url}}</a><br><br><strong>The Ketravelan Crew</strong></td></tr></table></td></tr></table></body></html>', 'You''re all set! 🎉

Hi {{recipient_name}},

Discover trips, connect with fellow travelers, and start planning your next adventure.

{{action_url}}

The Ketravelan Crew', 'Welcome to Ketravelan 🎉', 'Start planning your next adventure', '["recipient_name","action_url"]'::jsonb),
  -- send-feedback-confirmation
  ('feedback_received', 'Feedback received', 'We received your feedback: {{reference_code}}', 'We received your feedback: {{reference_code}}', '<!doctype html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width" /><title>Ketravelan</title></head><body style="margin:0;background:#f4f6f8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial"><div style="display:none;font-size:1px;color:#f4f6f8;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden">Your feedback was received by Ketravelan.</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 0;"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:520px;background:#ffffff;border-radius:16px;border:1px solid #e5e7eb;box-shadow:0 10px 28px rgba(15,23,42,.08);"><tr><td align="center" style="padding:24px 20px"><img src="https://ketravelan.com/ketravelan_logo.png" alt="Ketravelan" style="display:block;border:0;outline:none;text-decoration:none;height:28px;width:auto" /></td></tr><tr><td style="height:1px;background:#e5e7eb" aria-hidden="true"></td></tr><tr><td style="padding:28px"><h1 style="font-size:20px;font-weight:700;margin:0 0 8px;color:#020617;text-align:center">Feedback received</h1><div style="font-size:15px;line-height:1.65;color:#475569;margin-bottom:24px;text-align:center">Hi <strong>{{recipient_name}}</strong>,<br><br>Thanks for sending feedback to Ketravelan. We have successfully received your submission (reference <strong>{{reference_code}}</strong>) and our team will review it.</div><table role="presentation" cellspacing="0" cellpadding="0" width="100%"><tr><td align="center"><a href="{{action_url}}" target="_blank" style="display:inline-block;padding:14px 26px;border-radius:10px;background:#000000;color:#ffffff;text-decoration:none;font-weight:600">View Feedback</a></td></tr></table></td></tr><tr><td style="padding:24px 28px;font-size:12px;color:#64748b;line-height:1.6">You’re receiving this because you have a Ketravelan account.<br><br>If the button doesn’t work, copy this link:<br><a href="{{action_url}}" style="color:#2563eb;word-break:break-all">{{action_url}}</a><br><br><strong>The Ketravelan Crew</strong></td></tr></table></td></tr></table></body></html>', 'Feedback received

Hi {{recipient_name}},

Thanks for sending feedback to Ketravelan. Reference: {{reference_code}}.

{{action_url}}

The Ketravelan Crew', 'Feedback received', 'Reference {{reference_code}}', '["recipient_name","reference_code","action_url"]'::jsonb)
),
filled AS (
  UPDATE public.notification_templates t
  SET
    email_subject_template = COALESCE(NULLIF(t.email_subject_template, ''), s.email_subject_template),
    email_html_template    = COALESCE(NULLIF(t.email_html_template, ''), s.email_html_template),
    email_text_template    = COALESCE(NULLIF(t.email_text_template, ''), s.email_text_template),
    push_title_template    = COALESCE(NULLIF(t.push_title_template, ''), s.push_title_template),
    push_body_template     = COALESCE(NULLIF(t.push_body_template, ''), s.push_body_template),
    variables = CASE WHEN t.variables IS NULL OR t.variables = '[]'::jsonb THEN s.variables ELSE t.variables END
  FROM seed s
  WHERE t.type = s.type
  RETURNING t.type
)
INSERT INTO public.notification_templates
  (type, title_template, message_template, email_subject_template, email_html_template, email_text_template, push_title_template, push_body_template, variables, channels, is_active)
SELECT s.type, s.title_template, s.message_template, s.email_subject_template, s.email_html_template, s.email_text_template, s.push_title_template, s.push_body_template, s.variables,
       ARRAY['in_app', 'push', 'email']::text[], true
FROM seed s
WHERE NOT EXISTS (SELECT 1 FROM public.notification_templates t WHERE t.type = s.type);
